# Generated by Django 4.0.6 on 2022-07-17 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casted_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectionSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ONGOING', 'Ongoing'), ('CONCLUDED', 'Concluded')], max_length=10)),
                ('tallied_results', models.JSONField()),
                ('initiated_on', models.DateTimeField()),
                ('concluded_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elections.college')),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_renewed', models.BooleanField()),
                ('current_officials', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='RunningCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballot_number', models.PositiveSmallIntegerField()),
                ('is_disqualified', models.BooleanField()),
                ('disqualification_reason', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elections.candidate')),
                ('election_season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elections.electionseason')),
                ('government_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elections.governmentposition')),
            ],
        ),
        migrations.CreateModel(
            name='VotedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.ballot')),
                ('running_candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elections.runningcandidate')),
            ],
        ),
        migrations.CreateModel(
            name='OfferedPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_positions_to_fill', models.PositiveSmallIntegerField()),
                ('election_season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elections.electionseason')),
                ('government_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elections.governmentposition')),
            ],
        ),
        migrations.AddField(
            model_name='electionseason',
            name='offered_positions',
            field=models.ManyToManyField(through='elections.OfferedPosition', to='elections.governmentposition'),
        ),
        migrations.AddField(
            model_name='electionseason',
            name='running_candidates',
            field=models.ManyToManyField(through='elections.RunningCandidate', to='elections.candidate'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elections.college'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elections.politicalparty'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='election_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elections.electionseason'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
