# Generated by Django 4.1.3 on 2022-11-28 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsoneditor.fields.django3_jsonfield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=15)),
                ('party', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectionSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('CONCLUDED', 'Concluded')], max_length=10)),
                ('tallied_results', jsoneditor.fields.django3_jsonfield.JSONField(blank=True, null=True)),
                ('initiated_on', models.DateTimeField(blank=True, null=True)),
                ('concluded_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Election Season',
            },
        ),
        migrations.CreateModel(
            name='GovernmentPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='elections.college')),
            ],
            options={
                'verbose_name': 'Government Position',
            },
        ),
        migrations.CreateModel(
            name='RunningCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballot_number', models.PositiveSmallIntegerField()),
                ('is_disqualified', models.BooleanField()),
                ('disqualification_reason', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elections.candidate')),
                ('election_season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elections.electionseason')),
                ('government_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elections.governmentposition')),
            ],
        ),
        migrations.CreateModel(
            name='OfferedPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_positions_to_fill', models.PositiveSmallIntegerField()),
                ('election_season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elections.electionseason')),
                ('government_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elections.governmentposition')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elections.college'),
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casted_on', models.DateTimeField()),
                ('signature', models.TextField(blank=True, null=True)),
                ('public_key', models.TextField(blank=True, null=True)),
                ('election_season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elections.electionseason')),
                ('voted_candidates', models.ManyToManyField(to='elections.runningcandidate')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
