# Generated by Django 4.1.3 on 2023-01-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial_squashed_0003_electionseasonwinningcandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentposition',
            name='to_fill',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
