# Generated by Django 4.0.6 on 2022-10-26 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_alter_candidate_party_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electionseason',
            options={'verbose_name': 'Election Season'},
        ),
        migrations.AlterModelOptions(
            name='governmentposition',
            options={'verbose_name': 'Government Position'},
        ),
        migrations.AlterModelOptions(
            name='politicalparty',
            options={'verbose_name': 'Political Party', 'verbose_name_plural': 'Political Parties'},
        ),
    ]
