# Generated by Django 4.1.3 on 2023-01-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_governmentposition_to_fill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningcandidate',
            name='tallied_votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
