# Generated by Django 4.1.5 on 2023-01-23 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_alter_runningcandidate_tallied_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='college',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='elections.college'),
            preserve_default=False,
        ),
    ]
